dataset_name: 'bay_point'
window: 24

detrend: False
scale: True
scaling_axis: 'channels'
scaled_target: True

epochs: 300
samples_per_epoch: 5120  # 160 batch of 32
batch_size: 32
aggregate_by: ['mean']

model_name: 'brits'
d_hidden: 256